# Getting started with Pandas

1. Official Pandas tutorial (https://pandas.pydata.org/)
2. Pandas is one of the most used library for data science

In [1]:
import pandas as pd
import numpy as np


Pandas has two main data structures:

1. Series

2. Dataframe

In [2]:
# from pandas import Series, DataFrame

## **Series**
1. Sequence of values, similar to numpy array
2. Each data value is associated to a label
  - Left side represents the index (data labels)
  - Right side represents the data

### Create a Series

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
type(obj.values)

numpy.ndarray

In [6]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [7]:
type(obj.index)

pandas.core.indexes.range.RangeIndex

- We can specify the labels.

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
type(obj2.index)

pandas.core.indexes.base.Index

### Numpy-like operations
1. Filtering with a boolean array
2. Scalar multiplication
3. Applying math functions

They will preserve the index-value link

In [11]:
obj2['b']

np.int64(7)

In [12]:
obj2['b']=4

In [13]:
obj2['b']

np.int64(4)

In [14]:
obj2

d    4
b    4
a   -5
c    3
dtype: int64

In [15]:
obj2[:'a']    # obj2[:3]    ATTENZIONE!!!

d    4
b    4
a   -5
dtype: int64

In [16]:
type(obj2[:2])

pandas.core.series.Series

In [17]:
obj2

d    4
b    4
a   -5
c    3
dtype: int64

In [18]:
obj2[['c', 'a', 'd', 'd', 'a']]

c    3
a   -5
d    4
d    4
a   -5
dtype: int64

In [19]:
type(obj2[['c', 'a', 'd', 'd', 'a']])

pandas.core.series.Series

In [20]:
obj2>2

d     True
b     True
a    False
c     True
dtype: bool

In [21]:
type(obj2>2)

pandas.core.series.Series

In [22]:
obj2[obj2 > 2]

d    4
b    4
c    3
dtype: int64

In [23]:
type(obj2[obj2 > 2])

pandas.core.series.Series

In [24]:
'a' in obj2    # controllo se un valore è tra gli indici della Series

True

In [25]:
3 in obj2

False

In [26]:
3 in obj2.values    # controllo se un valore è tra i values della Series

True

In [27]:
obj2.isin([3])

d    False
b    False
a    False
c     True
dtype: bool

In [28]:
obj2 == 3

d    False
b    False
a    False
c     True
dtype: bool

In [29]:
(obj2 == 3).any()

np.True_

### Math operations

Element wise casting

Given $ X = \left[ x_1 \cdots x_n \right] $ then:<br> $ X * 2  = \left[ 2 x_1  \cdots 2{x_n} \right]
$
 <br> $
e^X = \left[ e^{x_1} \cdots e^{x_n} \right]
$



In [30]:
obj2

d    4
b    4
a   -5
c    3
dtype: int64

In [31]:
obj2 * 2

d     8
b     8
a   -10
c     6
dtype: int64

In [32]:
np.exp(obj2)

d    54.598150
b    54.598150
a     0.006738
c    20.085537
dtype: float64

### Use alignment of indexes for some operations

In [33]:
obj3 = pd.Series([1,2,3], index=['a', 'b', 'c'])

In [34]:
obj4 = pd.Series([1,2,3], index=['a', 'd', 'e'])

In [35]:
obj3 + obj4

a    2.0
b    NaN
c    NaN
d    NaN
e    NaN
dtype: float64

In [36]:
obj3.add(obj4, fill_value=0)

a    2.0
b    2.0
c    3.0
d    2.0
e    3.0
dtype: float64

### From Series to Dictionary and viceversa

- Another way to think about a Series is as a fixed-length, ordered dict, as it is a mapping of index values to data values.

In [37]:
obj2

d    4
b    4
a   -5
c    3
dtype: int64

In [38]:
obj2.to_dict()

{'d': 4, 'b': 4, 'a': -5, 'c': 3}

In [39]:
obj2.to_dict().keys()

dict_keys(['d', 'b', 'a', 'c'])

In [40]:
obj2.to_dict().values()

dict_values([4, 4, -5, 3])

- The index of the resulting Series will have the dict's keys
- The data values of the Series are the values of the dict

In [41]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [42]:
obj3.index

Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')

In [43]:
obj3.values

array([35000, 71000, 16000,  5000])

In [44]:
type(obj3)

pandas.core.series.Series

- Selecting the values of the Series based on the index values and forcing the order of the index

In [45]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [46]:
states = ['Ohio', 'California', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

Ohio          35000.0
California        NaN
Oregon        16000.0
Texas         71000.0
dtype: float64

In [47]:
pd.isnull(obj4)

Ohio          False
California     True
Oregon        False
Texas         False
dtype: bool

In [48]:
pd.notnull(obj4)

Ohio           True
California    False
Oregon         True
Texas          True
dtype: bool

In [49]:
obj4.isnull()

Ohio          False
California     True
Oregon        False
Texas         False
dtype: bool

### Dropping entries: method *.drop*

In [50]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [51]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [52]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [53]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [54]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Giving a name to the Series
- The name of the Series becomes its index or column name if it is used to form a DataFrame.
- It is also used whenever displaying the Series using the interpreter.

In [55]:
obj4.name = 'population'
obj4

Ohio          35000.0
California        NaN
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [56]:
obj4.index.name = 'state'

In [57]:
obj4

state
Ohio          35000.0
California        NaN
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## **DataFrame**
1. Represents a rectangular table of data
2. Contains an ordered collection of columns
3. Has indexes on columns and rows
4. Each column can have a different type (i.e., numeric, string, boolean, etc.)

### Create a Dataframe

In [58]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [59]:
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [60]:
frame.shape

(6, 3)

In [61]:
frame.head(3) # default: 5

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6


In [62]:
frame.tail(3)

,state,year,pop
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [63]:
frame.sample() # default: 1

,state,year,pop
5,Nevada,2003,3.2


In [64]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [65]:
frame.index.values

array([0, 1, 2, 3, 4, 5])

If you specify a sequence of columns, the DataFrame’s columns will be arranged in that order

In [66]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [67]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


Also, you can sepcify the row index.

In [68]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


In [69]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [70]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

### Indexing and Selection

- A column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute

In [71]:
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


In [72]:
frame2['state'] # by dict-like notation

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [73]:
type(frame2['state'])

pandas.core.series.Series

In [74]:
frame2.state # by attribute

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [75]:
frame2['year'][0] # or frame2.year[0]

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_14587/3019913084.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  frame2['year'][0] # or frame2.year[0]


np.int64(2000)

- Rows can also be retrieved by position or name with the special **loc** attribute

In [76]:
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


In [77]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [78]:
type(frame2.loc['three'])

pandas.core.series.Series

In [79]:
frame2.loc['three'][0]

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_14587/2260567952.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  frame2.loc['three'][0]


np.int64(2002)

Other options:
- ***loc***: Access a group of rows and columns by label(s).
- ***iloc***: Purely integer-location based rows and columns indexing for selection by position.
- **[   :   ,   :   ]**: Access rows by integer or labels, or access columns by labels (columns can be omitted).

In [80]:
data = pd.DataFrame(np.arange(20).reshape((4, 5)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['zero', 'one', 'two', 'three', 'four'])
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [81]:
data.loc['Ohio':'Colorado','two']

Ohio        2
Colorado    7
Name: two, dtype: int64

In [82]:
data[1:] # equals to
# data.loc['Colorado':]
# data.iloc[1:]

,zero,one,two,three,four
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [83]:
data[0:2] # --> [] by integer
# equals to
# data.loc['Ohio':'Colorado']
# data.iloc[0:2]
# data['Ohio':'Colorado'] # --> [] by label

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9


In [84]:
data[['one']]

,one
Ohio,1
Colorado,6
Utah,11
New York,16


In [85]:
data[['one','two']]

,one,two
Ohio,1,2
Colorado,6,7
Utah,11,12
New York,16,17


In [86]:
# data.loc['Colorado':'Utah','two':]# equal to
data.iloc[1:3,2:]

,two,three,four
Colorado,7,8,9
Utah,12,13,14


In [87]:
data.loc[:,'one'] # equal to data['one'] and data.one

Ohio         1
Colorado     6
Utah        11
New York    16
Name: one, dtype: int64

In [88]:
data[['three', 'two', 'one']] # equals to
# data.loc[:,['three', 'two', 'one']]
# data.iloc[:,[2,1,0]]

,three,two,one
Ohio,3,2,1
Colorado,8,7,6
Utah,13,12,11
New York,18,17,16


In [89]:
data.loc[:, 'two':] # or
#data.iloc[:, 2:]
# data['two':] does not work

,two,three,four
Ohio,2,3,4
Colorado,7,8,9
Utah,12,13,14
New York,17,18,19


In [90]:
data.loc['Colorado']
# data['Colorado'] # does not work >>> None of [Index(['Colorado'], dtype='object')] are in the [columns] <<< --> in [] single labels are only for columns
# data.iloc[1]

zero     5
one      6
two      7
three    8
four     9
Name: Colorado, dtype: int64

In [91]:
data.loc[['Colorado']]
# data['Colorado':'Colorado']
# data.iloc[[1]]

,zero,one,two,three,four
Colorado,5,6,7,8,9


In [92]:
# Row and columns selection
# Examples
data.loc['Ohio':'Colorado', 'three'] # data.loc[[row], [col]] -> label
data.loc['Colorado', ['two', 'three']] # data
data.loc['Ohio':'Colorado', 'three':'four']
data.iloc[[1, 2], 1:2]
data.loc[:'Utah', 'two']
data.iloc[0:2, :] # data.iloc[[row], [col]] -> posizionale
data.iloc[2:3, [3, 0, 1]] # Utah, cols: four, one, two

,three,zero,one
Utah,13,10,11


Why use loc? Differences between [] and .loc[]

1.   using **.loc**, the execution time is more than 3X times faster!

2.   loc is explicit: df.loc[row_indexer, column_index] can select rows and columns.

 df[indexer] can only select rows or columns depending on the type of values in indexer and the type of column values the dataframe has.

3.  When a slice is passed to **df.loc** the **end-points are included** in the range. When a slice is passed to **df[...]**, the slice is interpreted as a **half-open** interval.

In [93]:
x = pd.DataFrame(np.arange(9).reshape(3,3))
x

,0,1,2
0,0,1,2
1,3,4,5
2,6,7,8


In [94]:
x.loc[1:2].index.values

array([1, 2])

In [95]:
x[1:2].index.values

array([1])

### Filtering

In [96]:
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [97]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [98]:
data[data['three'] > 5]
# data.loc[data['three'] > 5]
# data.iloc[data['three'] > 5] # NOT working >>> iLocation based boolean indexing cannot use an indexable as a mask

,zero,one,two,three,four
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [99]:
data >= 12

,zero,one,two,three,four
Ohio,False,False,False,False,False
Colorado,False,False,False,False,False
Utah,False,False,True,True,True
New York,True,True,True,True,True


In [100]:
data[data >= 12]
# Does NOT work with loc & iloc

,zero,one,two,three,four
Ohio,NaN,NaN,NaN,NaN,NaN
Colorado,NaN,NaN,NaN,NaN,NaN
Utah,NaN,NaN,12.0,13.0,14.0
New York,15.0,16.0,17.0,18.0,19.0


In [101]:
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [102]:
data.iloc[:, :3] [(data.three > 5) & (data['four'] <15)] # combination

,zero,one,two
Colorado,5,6,7
Utah,10,11,12


### Modify a DataFrame

In [103]:
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [104]:
data_copy_reference = data

data_copy = data.copy()

data_view = data.iloc[2:,1:-1]

In [105]:
data_copy_reference

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [106]:
data_copy_reference[data_copy_reference >= 12] = 100
data_copy_reference

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,100,100,100
New York,100,100,100,100,100


In [107]:
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,100,100,100
New York,100,100,100,100,100


In [108]:
data_copy

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [109]:
data_view

,one,two,three
Utah,11,100,100
New York,100,100,100


- Columns can be modified by assignment.

In [110]:
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


In [111]:
frame2['debt'] = 16.5
frame2
# 16.5 is **broadcasted** to [16.5, 16.5, ...] == [16.5] * frame2['debt'].shape[0]

,year,state,pop,debt
one,2000,Ohio,1.5,16.5
two,2001,Ohio,1.7,16.5
three,2002,Ohio,3.6,16.5
four,2001,Nevada,2.4,16.5
five,2002,Nevada,2.9,16.5
six,2003,Nevada,3.2,16.5


- When you are assigning lists or arrays to a column, the value’s length must match the length of the DataFrame.

In [112]:
frame2['debt'] = [2,15.7,80,98,12,12]
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,2.0
two,2001,Ohio,1.7,15.7
three,2002,Ohio,3.6,80.0
four,2001,Nevada,2.4,98.0
five,2002,Nevada,2.9,12.0
six,2003,Nevada,3.2,12.0


In [113]:
# viene mantenuta l'associazione con i valori dell'indice

val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,-1.2
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,-1.5
five,2002,Nevada,2.9,-1.7
six,2003,Nevada,3.2,NaN


### Dropping entries from an axis: method *.drop*

In [114]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [115]:
data.drop(['Colorado', 'Ohio'])

,one,two,three,four
Utah,8,9,10,11
New York,12,13,14,15


In [116]:
data.drop(['two', 'four'], axis=1)

,one,three
Ohio,0,2
Colorado,4,6
Utah,8,10
New York,12,14


Reminder: Se si vuole che la drop abbia effetto:
- o si passa l'espressione ad un nuovo dataframe, `new = data.drop(['Colorado', 'Ohio'])`
- o si imposta inplace=True, `data.drop(['Colorado', 'Ohio'], inplace=True)`

In [117]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


### Arithmetic and Data Alignment

In [118]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [119]:
df1

,b,c,d
Ohio,0.0,1.0,2.0
Texas,3.0,4.0,5.0
Colorado,6.0,7.0,8.0


In [120]:
df2

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [121]:
df1 + df2

,b,c,d,e
Colorado,NaN,NaN,NaN,NaN
Ohio,3.0,NaN,6.0,NaN
Oregon,NaN,NaN,NaN,NaN
Texas,9.0,NaN,12.0,NaN
Utah,NaN,NaN,NaN,NaN


#### Arithmetic methods with fill values

In [122]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [123]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [124]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,6.0,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [125]:
df2.loc[1, 'b'] = np.nan

In [126]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,NaN,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [127]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [128]:
df1-df2

,a,b,c,d,e
0,0.0,0.0,0.0,0.0,NaN
1,-1.0,NaN,-1.0,-1.0,NaN
2,-2.0,-2.0,-2.0,-2.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [129]:
df1.sub(df2, fill_value=12000)

,a,b,c,d,e
0,0.0,0.0,0.0,0.0,11996.0
1,-1.0,-11995.0,-1.0,-1.0,11991.0
2,-2.0,-2.0,-2.0,-2.0,11986.0
3,11985.0,11984.0,11983.0,11982.0,11981.0


In [130]:
1 / df1

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [131]:
df1 * 144

,a,b,c,d
0,0.0,144.0,288.0,432.0
1,576.0,720.0,864.0,1008.0
2,1152.0,1296.0,1440.0,1584.0


In [132]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


### Re-indexing

In [133]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [134]:
df1.reindex(columns=['a', 'd', 'b', 'f'], fill_value=100)

,a,d,b,f
0,0.0,3.0,1.0,100
1,4.0,7.0,5.0,100
2,8.0,11.0,9.0,100


## Operations between DataFrame and Series

In [135]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [136]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [137]:
frame + series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


In [138]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [139]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [140]:
frame + series3

,Ohio,Oregon,Texas,Utah,b,d,e
Utah,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ohio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oregon,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [141]:
frame.add(series3, axis='index')

,b,d,e
Utah,1.0,2.0,3.0
Ohio,7.0,8.0,9.0
Texas,13.0,14.0,15.0
Oregon,19.0,20.0,21.0


### Function Application and Mapping

- *apply*: Apply a function along an axis of the DataFrame
- *map*: Apply a function to a Dataframe elementwise. This method applies a function that accepts and returns a scalar to every element of a DataFrame

In [142]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

,b,d,e
Utah,-0.018609,-0.144933,0.545831
Ohio,0.814741,-0.791369,-0.405869
Texas,-1.331043,0.870171,-0.763464
Oregon,-0.249782,1.137576,0.145216


In [143]:
frame['b'].max()

0.8147406194286271

In [144]:
frame['b'].min()

-1.3310425052958577

In [145]:
frame

,b,d,e
Utah,-0.018609,-0.144933,0.545831
Ohio,0.814741,-0.791369,-0.405869
Texas,-1.331043,0.870171,-0.763464
Oregon,-0.249782,1.137576,0.145216


In [146]:
def diff_max_min(x): # x pd.Series
  return x.max() - x.min()  # default is axis=0

In [147]:
frame.apply(diff_max_min)

b    2.145783
d    1.928945
e    1.309295
dtype: float64

In [148]:
frame.apply(lambda x: x.max() - x.min())

b    2.145783
d    1.928945
e    1.309295
dtype: float64

In [149]:
frame.apply(diff_max_min, axis='columns') # or axis=1

Utah      0.690764
Ohio      1.606109
Texas     2.201213
Oregon    1.387358
dtype: float64

In [150]:
def get_power_2(x): # x valore
  return np.power(x, 2)

frame.map(get_power_2)

,b,d,e
Utah,0.000346,0.021006,0.297932
Ohio,0.663802,0.626265,0.164729
Texas,1.771674,0.757197,0.582878
Oregon,0.062391,1.294079,0.021088


## Summarizing and Computing Descriptive Statistics

### Describe

- describe
- sum or cumsum
- mean
- count
- value_counts

In [151]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [152]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   one     3 non-null      float64
 1   two     2 non-null      float64
dtypes: float64(2)
memory usage: 96.0+ bytes


In [154]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [155]:
df.sum() # default axis=0

one    9.25
two   -5.80
dtype: float64

In [156]:
df.sum(axis='columns') # or axis=1

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [157]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [158]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [159]:
df.max()

one    7.1
two   -1.3
dtype: float64

In [160]:
df.idxmax()

one    b
two    d
dtype: object

### Unique Values, Value Counts, and Membership

In [161]:
obj = pd.Series(['c', 'a', 'c', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    c
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [162]:
uniques = obj.unique()
uniques

array(['c', 'a', 'b'], dtype=object)

In [163]:
obj.value_counts()

c    4
a    3
b    2
Name: count, dtype: int64

In [164]:
obj

0    c
1    a
2    c
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [165]:
obj.map(lambda x: x in ['c', 'a'])

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7     True
8     True
dtype: bool

In [166]:
mask = obj.isin(['c', 'a'])

In [167]:
mask

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7     True
8     True
dtype: bool

In [168]:
obj[mask]

0    c
1    a
2    c
3    a
4    a
7    c
8    c
dtype: object

In [169]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

,Qu1,Qu2,Qu3
0,1,2,1
1,3,3,5
2,4,1,2
3,3,2,4
4,4,3,4


In [170]:
pd.value_counts(data["Qu1"])

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_14587/4286318968.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data["Qu1"])


Qu1
3    2
4    2
1    1
Name: count, dtype: int64