In [1]:
import pandas as pd
import numpy as np

- In Data Analysis, a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging.
    - Such tasks are often reported to take up 80% or more of an analyst’s time.
- Pandas provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.
- Much of the design and implementation of pandas has been driven by the needs of real-world applications.

## Handling Missing Data
- Missing data occurs commonly in many data analysis applications.
    - All of the descriptive statistics on pandas objects exclude missing data by default.
- The missing data is represented in pandas with the floating-point value NaN (Not a Number).
    - We call this a sentinel value that can be easily detected.

- In pandas, missing data is also referred  as  NA (i.e., "not available").
- In statistics applications, NA means
    - data that does not exist
    - data that exists but was not observed

- When cleaning up data for analysis, it is often important to do analysis on the missing data itself to identify data
collection problems or potential biases in the data caused by missing data.
- The built-in Python None value is also treated as NA

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [7]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

Note that both None and NaN are considered null values.

### Filtering Out Missing Data

- dropna: Remove missing values.

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [9]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [12]:
data.notnull()

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [13]:
#dropna is equivalent to
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

- dropna in Dataframe

In [14]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [15]:
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [16]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [17]:
cleaned = data.dropna(axis=1)

In [18]:
cleaned

""
0
1
2
3


In [19]:
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


- Passing how='all' will only drop rows that are all NA

In [20]:
data.dropna(how='all')

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [21]:
data.dropna(how='any')    # default

,0,1,2
0,1.0,6.5,3.0


- if you want to keep only rows containing a certain number of observations.

In [22]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan

In [23]:
df

,0,1,2
0,0.469716,NaN,NaN
1,-0.047827,NaN,NaN
2,-0.437290,NaN,0.416937
3,1.132443,NaN,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


In [24]:
df.dropna(thresh=2)

,0,1,2
2,-0.437290,NaN,0.416937
3,1.132443,NaN,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


### Filling In Missing Data

- *fillna*: Fill NA/NaN values using the specified method

In [25]:
df

,0,1,2
0,0.469716,NaN,NaN
1,-0.047827,NaN,NaN
2,-0.437290,NaN,0.416937
3,1.132443,NaN,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


In [26]:
df.fillna(42)

,0,1,2
0,0.469716,42.000000,42.000000
1,-0.047827,42.000000,42.000000
2,-0.437290,42.000000,0.416937
3,1.132443,42.000000,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


In [27]:
df

,0,1,2
0,0.469716,NaN,NaN
1,-0.047827,NaN,NaN
2,-0.437290,NaN,0.416937
3,1.132443,NaN,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


In [28]:
#if the value to fill in depends on the column
df.fillna({1: 0.5, 2: 0})

,0,1,2
0,0.469716,0.500000,0.000000
1,-0.047827,0.500000,0.000000
2,-0.437290,0.500000,0.416937
3,1.132443,0.500000,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


In [29]:
df

,0,1,2
0,0.469716,NaN,NaN
1,-0.047827,NaN,NaN
2,-0.437290,NaN,0.416937
3,1.132443,NaN,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


In [30]:
df.fillna(0, inplace=True)

In [31]:
df

,0,1,2
0,0.469716,0.000000,0.000000
1,-0.047827,0.000000,0.000000
2,-0.437290,0.000000,0.416937
3,1.132443,0.000000,0.180571
4,-0.106980,-1.863697,-0.397366
5,0.736981,-0.391901,0.160219
6,0.372476,-0.396847,0.467326


- computing a value

In [32]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

,0,1,2
0,1.402704,0.099286,0.725629
1,-0.230618,-1.487912,0.932643
2,0.098617,NaN,1.210544
3,-0.429829,NaN,-2.201089
4,-1.107249,NaN,NaN
5,-0.698178,NaN,NaN


In [33]:
df.fillna(method='ffill')

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_26965/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


,0,1,2
0,1.402704,0.099286,0.725629
1,-0.230618,-1.487912,0.932643
2,0.098617,-1.487912,1.210544
3,-0.429829,-1.487912,-2.201089
4,-1.107249,-1.487912,-2.201089
5,-0.698178,-1.487912,-2.201089


In [34]:
df.ffill() # ffill: propagate last valid observation forward to next valid.

,0,1,2
0,1.402704,0.099286,0.725629
1,-0.230618,-1.487912,0.932643
2,0.098617,-1.487912,1.210544
3,-0.429829,-1.487912,-2.201089
4,-1.107249,-1.487912,-2.201089
5,-0.698178,-1.487912,-2.201089


In [35]:
#limit for forward and backward filling, maximum number of consecutive periods to fill
df.fillna(method='ffill', limit=2)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_26965/2783928219.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)


,0,1,2
0,1.402704,0.099286,0.725629
1,-0.230618,-1.487912,0.932643
2,0.098617,-1.487912,1.210544
3,-0.429829,-1.487912,-2.201089
4,-1.107249,NaN,-2.201089
5,-0.698178,NaN,-2.201089


In [36]:
#we can use other functions
df.fillna(df.mean())

,0,1,2
0,1.402704,0.099286,0.725629
1,-0.230618,-1.487912,0.932643
2,0.098617,-0.694313,1.210544
3,-0.429829,-0.694313,-2.201089
4,-1.107249,-0.694313,0.166932
5,-0.698178,-0.694313,0.166932


In each column the substitution is done with that feature's mean.

In [37]:
df.mean()

0   -0.160759
1   -0.694313
2    0.166932
dtype: float64

Value on index 0 is the mean of column 0, value on index 1 is the mean of column 1, ... .

## Data Transformation


### Removing Duplicates

- *duplicated*
- drop_duplicated

In [38]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [39]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
# data['k1'].duplicated() is equivalent to
data.duplicated(['k1'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
dtype: bool

In [41]:
data.drop_duplicates()

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [42]:
data['v1'] = range(7)
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [43]:
data.drop_duplicates(['k1', 'k2'], keep='last')

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
6,two,4,6


### Transforming Data Using a Function or Mapping

- map: Map values of Series according to input correspondence.

In [44]:
data = pd.DataFrame({
    'device': ['iPhone', 'Galaxy S21', 'MacBook Pro', 'Pixel 6',
               'ThinkPad', 'iPad', 'Surface Pro', 'galaxy tab', 'Macbook air'],
    'price': [999, 799, 1299, 599, 1099, 799, 999, 649, 999]
})

1. passing dictionary

In [45]:
device_to_brand = {
    'iphone': 'Apple',
    'macbook pro': 'Apple',
    'macbook air': 'Apple',
    'ipad': 'Apple',
    'galaxy s21': 'Samsung',
    'galaxy tab': 'Samsung',
    'pixel 6': 'Google',
    'thinkpad': 'Lenovo',
    'surface pro': 'Microsoft'
}

In [46]:
data['brand'] = data['device'].str.lower().map(device_to_brand)
data

,device,price,brand
0,iPhone,999,Apple
1,Galaxy S21,799,Samsung
2,MacBook Pro,1299,Apple
3,Pixel 6,599,Google
4,ThinkPad,1099,Lenovo
5,iPad,799,Apple
6,Surface Pro,999,Microsoft
7,galaxy tab,649,Samsung
8,Macbook air,999,Apple


### Replacing Values

- *replace*: Replace values given in *to_replace* with value.

In [47]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [48]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [49]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [50]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [51]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Discretization and Binning

- *cut*: Bin values into discrete intervals. Use cut when you need to segment and sort data values into bins

In [52]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 59, 45, 41, 32]

In [53]:
bins = [18, 25, 35, 60, 100]

In [54]:
values = pd.cut(ages, bins)

In [55]:
values

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 60], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [56]:
type(values)

pandas.core.arrays.categorical.Categorical

In [57]:
values.codes # indexes of the bins

array([0, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1], dtype=int8)

In [58]:
values.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [59]:
values

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 60], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [60]:
#These are the bin counts for the result of pandas.cut.
pd.value_counts(values)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_26965/4026612463.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


(18, 25]     5
(35, 60]     4
(25, 35]     3
(60, 100]    0
Name: count, dtype: int64

In [61]:
pd.Series(values).value_counts()

(18, 25]     5
(35, 60]     4
(25, 35]     3
(60, 100]    0
Name: count, dtype: int64

In [62]:
#parenthesis means that the side is open,
#while the square bracket means it is closed (inclusive).
#You can change which side is closed by passing right=False:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [36, 61), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [63]:
#You can also pass your own bin names by passing a list or array to the labels option:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
new_ages = pd.cut(ages, bins, labels=group_names)

In [64]:
new_ages.categories

Index(['Youth', 'YoungAdult', 'MiddleAged', 'Senior'], dtype='object')

In [65]:
pd.value_counts(new_ages)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_26965/2959182787.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(new_ages)


Youth         5
MiddleAged    4
YoungAdult    3
Senior        0
Name: count, dtype: int64

In [66]:
# passing an integer, it will compute
#equal-length bins based on the minimum and maximum values in the data.
data = np.random.rand(20)
data

array([0.66070602, 0.70003058, 0.39958103, 0.62900041, 0.08553964,
       0.01192457, 0.50114949, 0.5885616 , 0.75030757, 0.60455965,
       0.46440052, 0.82894577, 0.5924218 , 0.42035257, 0.66050447,
       0.85912932, 0.48253411, 0.09751806, 0.15020599, 0.98375833])

In [67]:
pd.cut(data, 13).codes # takes minimum and maximum values, divides that interval in equal sized bins

array([ 8,  9,  5,  8,  0,  0,  6,  7,  9,  7,  6, 10,  7,  5,  8, 11,  6,
        1,  1, 12], dtype=int8)

In [68]:
pd.cut(data, 13).categories

IntervalIndex([(0.011, 0.0867], (0.0867, 0.161],  (0.161, 0.236],
                (0.236, 0.311],  (0.311, 0.386],   (0.386, 0.46],
                 (0.46, 0.535],   (0.535, 0.61],   (0.61, 0.685],
                (0.685, 0.759],  (0.759, 0.834],  (0.834, 0.909],
                (0.909, 0.984]],
              dtype='interval[float64, right]')

### Computing Indicator/Dummy Variables/ One Hot Encoding (OHE)
- This converts a categorical variable into a “dummy” or “indicator” matrix.

- If a column in a DataFrame has k distinct values,
    - you would derive a matrix or DataFrame with k columns containing all 1s and 0s.
- pandas has a get_dummies function for doing this

In [69]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [70]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [71]:
pd.get_dummies(df['key']) # dtype='bool' is default

,a,b,c
0,False,True,False
1,False,True,False
2,True,False,False
3,False,False,True
4,True,False,False
5,False,True,False


In [72]:
pd.get_dummies(df['key'], dtype='int')

,a,b,c
0,0,1,0
1,0,1,0
2,1,0,0
3,0,0,1
4,1,0,0
5,0,1,0


In [73]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [74]:
dummies

,key_a,key_b,key_c
0,False,True,False
1,False,True,False
2,True,False,False
3,False,False,True
4,True,False,False
5,False,True,False


In [75]:
df[['data1']]

,data1
0,0
1,1
2,2
3,3
4,4
5,5


In [76]:
#to join the result in the original dataframe
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

,data1,key_a,key_b,key_c
0,0,False,True,False
1,1,False,True,False
2,2,True,False,False
3,3,False,False,True
4,4,True,False,False
5,5,False,True,False
